## Numpy

Numpy is a general purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays.

pip install
import numpy
numpy.__version__

## array creation

In [2]:
import numpy as np
a=np.array([1,2,5,9,0])
print(a)
print(a.dtype)
print(a.shape)
print(a[0])
a[0]=6
print(a)

[1 2 5 9 0]
int32
(5,)
1
[6 2 5 9 0]


In [2]:
a=np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
a=np.array([[1,2,3,4]])
print(a)
print(a.shape)
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.shape)
print(type(a))
print(a[0,1])
a[0,1]=5
print(a)
print(a[1,3])
a[1,3]=3
print(a)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1 2 3 4]]
(1, 4)
[[1 2 3 4]
 [6 7 8 9]]
(2, 4)
<class 'numpy.ndarray'>
2
[[1 5 3 4]
 [6 7 8 9]]
9
[[1 5 3 4]
 [6 7 8 3]]


In [4]:
list1=[1,2,3,4,5]
list2=[[1,2,3,4],[5,6,7,8]]
print(list2[0][2])
list2[0][2]=[4,5]
print(list2[0][2])
a=np.array(list1)
b=np.array(list2)
print(a)
print(a.shape)
print(b)
print(b.shape)

3
[4, 5]
[1 2 3 4 5]
(5,)
[[1 2 list([4, 5]) 4]
 [5 6 7 8]]
(2, 4)


## Array functions

In [4]:
list1=[1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
print(a.reshape(2,5))
print(a.reshape(5,2))
print(a.reshape(2,-3)) #the -ve value will be ignored and array will be made acc to 2 rows
print(a.reshape(-3,2)) #the -ve value will be ignored and array will be made acc to 2 columns
print(a.reshape(-1,1))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


## ravel

In [5]:
list1=[1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
b=a.reshape(2,5)
print(b)
print(b.ravel()) #this will convert the whole array to 1 d array (aka 1 row) 

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


## Tolist

In [6]:
list1=[1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
print(type(a))
a=a.reshape(5,-1)
print(a)
b=a.tolist() #convert array to list
print(b)
print(type(b))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
<class 'list'>


In [7]:
tupple1=(1,2,3,4,5,6,7,8,9,10)
a=np.array(tupple1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## data type conversion

In [8]:
a=np.array([1,2])
print(a)
print(a.dtype)

a=np.array([1.2,2.2])
print(a)
print(a.dtype)

a=np.array([1,2],dtype=float)
print(a)
print(a.dtype)

a=np.array([1.2,2.2],dtype=int)
print(a)
print(a.dtype)

[1 2]
int32
[1.2 2.2]
float64
[1. 2.]
float64
[1 2]
int32


## frequently used matrices

In [9]:
a=np.zeros((2,2))
print(a)
print(a.dtype)
b=np.zeros((2,2),dtype=int)
print(b)
print(b.dtype)
a=np.ones((2,2))
print(a)
print(a.dtype)
a=np.ones((2,2),dtype=int)
print(a)
print(a.dtype)
a=np.full((3,4),4)
print(a)
a=np.full((3,4),4,dtype=float)
print(a)
a=np.eye(4)
print(a)
a=np.eye(4,dtype=int)
print(a)

[[0. 0.]
 [0. 0.]]
float64
[[0 0]
 [0 0]]
int32
[[1. 1.]
 [1. 1.]]
float64
[[1 1]
 [1 1]]
int32
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
a=np.random.random((3,3))
print(a)
a=np.random.randint(5,10,size=(3,3))
print(a)

[[0.04600854 0.79130304 0.59226082]
 [0.64367484 0.00230393 0.85928965]
 [0.83722858 0.72613892 0.9871808 ]]
[[5 8 5]
 [8 5 5]
 [9 7 5]]


## array slicing

In [11]:
import numpy as nb
a=nb.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[0:2,1:3])
print(a[:-2,:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[1 2 3]]


In [12]:
a=nb.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[::2,1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4]
 [10 12]]


In [13]:
a=nb.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[:-1,[0,1,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 4]
 [5 6 8]]


## Boolean indexing

In [14]:
import numpy as nc
a=nc.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a>5
print(b)
print(a[b])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]


## Array operations

In [15]:
a=nc.array([[1,2],[3,4]])
b=nc.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b)
print(nc.add(a,b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [16]:
a=nc.array([[1,2],[3,4]])
b=nc.array([[5,6],[7,8]])
print(a)
print(b)
print(a-b)
print(nc.subtract(b,a))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -4]]
[[4 4]
 [4 4]]


In [17]:
a=nc.array([[1,2],[3,4]])
b=nc.array([[5,6],[7,8]])
print(a)
print(b)
print(a*b)
print(nc.multiply(a,b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [18]:
a=nc.array([[1,2],[3,4]])
b=nc.array([[5,6],[7,8]])
print(a)
print(b)
print(a/b)
print(nc.divide(b,a))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[5.         3.        ]
 [2.33333333 2.        ]]


In [19]:
a=nc.array([[4,25],[9,16]])
print(a)
print(nc.sqrt(a))

[[ 4 25]
 [ 9 16]]
[[2. 5.]
 [3. 4.]]


In [20]:
a=nc.array([[1,2],[3,4]])
b=nc.array([[5,6],[7,8]])
print(a)
print(b)
v=nc.array([9,10])
w=nc.array([11,12])
print(v)
print(w)
print(v.dot(w)) #dot product
print(nc.dot(v,w))
print(a.dot(v))
print(nc.dot(a,v))
print(a.dot(b))
print(nc.dot(a,b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [21]:
a=nc.array([[1,2],[3,4]])
print(a)
print(nc.sum(a)) #sum of all elements
print(nc.sum(a, axis=0))
print(nc.sum(a, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [22]:
print(a)
print(a.T) #transpose

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
